version: '3'

services:
  inmobiliaria-service:
    image: inmobiliaria-service
    volumes:
      - /serverfile:/serverfile
    ports:
      - 8080:8080
      - 587:587
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - inmo-red
networks:
  inmo-red:
    name: inmo-red