version: '3'

services:
  inmobiliaria-service:
    image: inmobiliaria-service
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - inmo-red
networks:
  inmo-red:
    name: inmo-red