spring:
  application:
    name: services
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://mysql-inmo:3306/inmobiliaria?useSSL=false
    username: testuser
    password: M!bN2d#S#!w3qCGbxEdSYyY&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080
  servlet:
    context-path: /services
app:
  jwtSecret: jwtSecretKey
  jwtExpiration: 86400  
  urlChangePassword: http://admin.yoreparocpu.xyz/recordar-contrasenia-cambio
  files: /serverfile